services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: penguinsDB
    ports:
      - 5432:5432
    # volumes:
    #   - ./db-data/:/var/lib/postgresql/data/
  web:
    build: .
    command: bash -c "dvc pull && python src/preprocess.py && python src/train.py && python src/predict.py -m SVM -t func && coverage run src/unit_tests/test_preprocess.py && coverage run -a src/unit_tests/test_training.py && coverage report -m && fastapi dev src/api/api.py --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    image: borisvikvik/borisvikvik-penguins-data-science:latest
    platform: linux/amd64
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # web:
  #   ports: 
  #     - 8000:8001
  #   image: borisvikvik/borisvikvik-penguins-data-science:latest
