pipeline{
    agent any
    environment{
        PATH = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:$PATH"
        DOCKERHUB_CREDS = credentials('Penguins-data-science')
    }
    stages{
        stage('Login'){
            steps{
                // sh 'source .env'
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
                }
        }
        stage('Pull image'){
            steps{
                sh 'docker pull borisvikvik/borisvikvik-penguins-data-science-2lab'
            }
        }
        stage('Run container'){
            steps{
                sh 'docker compose up -d'
                sh 'sleep 30 && docker compose down'
                // sh 'docker run --name penguins-data-science -p 8080:5556'
            }
        }
    }
    post{
        always{
            sh 'docker logout'
        }
    }
}
