pipeline {
    agent any
    environment {
        PATH = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:$PATH"
        DOCKERHUB_CREDS = credentials('Penguins-data-science')
    }
    stages {
        stage('Clone github repository') {
            steps {
                // cleanWs()
                
                sh '''
                    dvc pull
                '''
                // sh 'dvcpull'
				}
			}

        stage('Checkout repo dir') {
            steps {
                sh 'ls'
				}
			}
        stage('Login'){
            steps{
                // sh 'source .env'
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
                }
            }

        stage('Create and run docker container') {
            steps {
                script {
                    try {
                        sh 'docker compose build'
                        }

                    finally {
                    sh '''
                        
                        docker compose up -d
                        '''
                        }
				    }
                }
            }
        stage('Push')
        {
            steps{
                sh 'docker push borisvikvik/borisvikvik-penguins-data-science-2lab:latest'
            }
        }
        
    }
    post{
        always{
            sh 'ls && docker compose stop && docker logout'
        }
    }

}
